[tool.poetry]
name = "cielo"
version = "0.1.0"
description = "CIELO – Cloud Infrastructure, Environment, and Lifecycle Orchestrator"
authors = ["Your Name <you@example.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
django = "^5.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
