# Generated by Django 5.2.1 on 2025-05-28 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StorageAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Location')),
                ('sku', models.CharField(blank=True, max_length=50, verbose_name='SKU')),
                ('access_tier', models.CharField(blank=True, max_length=50, verbose_name='Access Tier')),
            ],
            options={
                'verbose_name': 'Storage Account',
                'verbose_name_plural': 'Storage Accounts',
            },
        ),
        migrations.CreateModel(
            name='VirtualMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Location')),
                ('environment', models.CharField(blank=True, max_length=50, verbose_name='Environment')),
            ],
            options={
                'verbose_name': 'Virtual Machine',
                'verbose_name_plural': 'Virtual Machines',
            },
        ),
    ]
