# Generated by Django 5.2.1 on 2025-05-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AzureSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Subscription Name')),
                ('subscription_id', models.CharField(help_text='The unique GUID for the Azure Subscription.', max_length=36, unique=True, verbose_name='Azure Subscription ID')),
            ],
            options={
                'verbose_name': 'Azure Subscription',
                'verbose_name_plural': 'Azure Subscriptions',
                'ordering': ['name'],
            },
        ),
    ]
