# Generated by Django 5.2.1 on 2025-05-28 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_azuresubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualmachine',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='virtual_machines', to='inventory.azuresubscription'),
        ),
    ]
